# Generated by Django 5.2 on 2025-04-08 23:05

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomcategory')),
            ],
        ),
    ]
