# Generated by Django 5.2 on 2025-04-14 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_room'),
        ('rooms', '0003_roomcategoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomcategory'),
            preserve_default=False,
        ),
    ]
