# Generated by Django 5.2 on 2025-04-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
